# Generated by Django 5.1.14 on 2025-11-09 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.FloatField(help_text='kcal / 100g')),
                ('proteins', models.FloatField(help_text='g / 100g')),
                ('carbs', models.FloatField(help_text='g / 100g')),
                ('fats', models.FloatField(help_text='g / 100g')),
                ('fiber', models.FloatField(default=0, help_text='g / 100g')),
                ('portion_size', models.FloatField(default=100, help_text='g')),
                ('meal_type', models.CharField(blank=True, choices=[('mic_dejun', 'Mic dejun'), ('gustare1', 'Gustare 1'), ('pranz', 'Prânz'), ('gustare2', 'Gustare 2'), ('cina', 'Cinǎ')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MacroRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('proteins', models.FloatField(help_text='% din calorii')),
                ('carbs', models.FloatField(help_text='% din calorii')),
                ('fats', models.FloatField(help_text='% din calorii')),
                ('fiber_per_day', models.FloatField(default=30, help_text='g fibre/zi')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('weight', models.FloatField(help_text='kg')),
                ('height', models.FloatField(blank=True, help_text='cm', null=True)),
                ('activity_level', models.CharField(choices=[('sedentar', 'Sedentar'), ('usor', 'Activitate ușoară'), ('moderata', 'Activitate moderată'), ('intensa', 'Activitate intensă'), ('foarte_intensa', 'Foarte intensă')], max_length=20)),
            ],
        ),
    ]
