# Generated by Django 5.1.14 on 2025-12-24 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('proteins', models.PositiveSmallIntegerField()),
                ('carbs', models.PositiveSmallIntegerField()),
                ('fats', models.PositiveSmallIntegerField()),
                ('fiber_recommendation', models.CharField(default='14g / 1000 kcal', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories', models.PositiveIntegerField()),
                ('proteins', models.PositiveIntegerField()),
                ('carbs', models.PositiveIntegerField()),
                ('fats', models.PositiveIntegerField()),
                ('fiber', models.PositiveIntegerField()),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('target_weight', models.FloatField(blank=True, null=True)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentar'), ('light', 'Activitate ușoară'), ('moderate', 'Activitate moderată'), ('active', 'Activitate intensă'), ('very_active', 'Foarte intensă')], default='moderate', max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('user_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('macro_ratio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.macroratio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_restaurants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meal_type', models.CharField(choices=[('mic_dejun', 'Mic dejun'), ('gustare1', 'Gustare 1'), ('pranz', 'Prânz'), ('gustare2', 'Gustare 2'), ('cina', 'Cinǎ')], max_length=20)),
                ('calories', models.PositiveIntegerField(help_text='kcal per 100g')),
                ('proteins', models.DecimalField(decimal_places=1, help_text='g per 100g', max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=1, help_text='g per 100g', max_digits=5)),
                ('fats', models.DecimalField(decimal_places=1, help_text='g per 100g', max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/')),
                ('is_default', models.BooleanField(default=False, help_text='Dacă este bifat, acest aliment este disponibil pentru TOATE restaurantele')),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='core.restaurant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'restaurant')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Proprietar'), ('admin', 'Administrator'), ('staff', 'Personal')], default='staff', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.restaurant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'restaurant')},
            },
        ),
    ]
