# Generated by Django 5.1.14 on 2025-11-28 16:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('calories', models.FloatField(help_text='kcal / 100g')),
                ('proteins', models.FloatField(help_text='g / 100g')),
                ('carbs', models.FloatField(help_text='g / 100g')),
                ('fats', models.FloatField(help_text='g / 100g')),
                ('fiber', models.FloatField(default=0)),
                ('portion_size', models.FloatField(default=100)),
                ('meal_type', models.CharField(blank=True, choices=[('mic_dejun', 'Mic dejun'), ('gustare1', 'Gustare 1'), ('pranz', 'Prânz'), ('gustare2', 'Gustare 2'), ('cina', 'Cinǎ')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MacroRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('proteins', models.PositiveSmallIntegerField()),
                ('carbs', models.PositiveSmallIntegerField()),
                ('fats', models.PositiveSmallIntegerField()),
                ('fiber_recommendation', models.CharField(default='14g / 1000 kcal', max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)])),
                ('weight', models.FloatField(help_text='kg')),
                ('height', models.FloatField(blank=True, help_text='cm', null=True)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentar'), ('light', 'Activitate ușoară'), ('moderate', 'Activitate moderată'), ('active', 'Activitate intensă'), ('very_active', 'Foarte intensă')], default='moderate', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories', models.PositiveIntegerField()),
                ('proteins', models.PositiveIntegerField()),
                ('carbs', models.PositiveIntegerField()),
                ('fats', models.PositiveIntegerField()),
                ('fiber', models.PositiveIntegerField()),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('target_weight', models.FloatField(blank=True, null=True)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentar'), ('light', 'Activitate ușoară'), ('moderate', 'Activitate moderată'), ('active', 'Activitate intensă'), ('very_active', 'Foarte intensă')], default='moderate', max_length=20)),
                ('user_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('macro_ratio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.macroratio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_mealpl_user_id_d01629_idx')],
            },
        ),
    ]
