# Generated by Django 5.1.14 on 2025-11-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mealplan',
            name='core_mealpl_user_id_d01629_idx',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
