# Generated by Django 5.1.14 on 2025-12-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='fiber',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='g fibre per 100g', max_digits=5),
        ),
    ]
