# Generated by Django 5.1.14 on 2025-11-09 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Bărbat'), ('F', 'Femeie')], max_length=1)),
                ('weight', models.FloatField()),
                ('height', models.FloatField(blank=True, null=True)),
                ('activity_level', models.CharField(max_length=20)),
                ('daily_calories', models.PositiveIntegerField()),
                ('proteins', models.PositiveIntegerField()),
                ('carbs', models.PositiveIntegerField()),
                ('fats', models.PositiveIntegerField()),
                ('fiber', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('macro_ratio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.macroratio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
