# Generated by Django 5.1.14 on 2025-12-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dish_fiber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='is_gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_lactose_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_raw_vegan',
            field=models.BooleanField(default=False, help_text='Raw și vegan'),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_vegan',
            field=models.BooleanField(default=False, help_text='Fără produse animale'),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_vegetarian',
            field=models.BooleanField(default=False, help_text='Fără carne, dar poate lactate/ouă'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='dietary_constraints',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='core.allergen'),
        ),
    ]
