# Generated by Django 5.1.14 on 2025-11-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_mealplan_core_mealpl_user_id_d01629_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
