# Generated by Django 5.1.14 on 2025-11-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mealplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroratio',
            name='description',
            field=models.CharField(blank=True, help_text='Explicație scurtă pentru utilizator', max_length=200),
        ),
        migrations.AlterField(
            model_name='macroratio',
            name='carbs',
            field=models.FloatField(help_text='Procentaj carbohidrați (%)'),
        ),
        migrations.AlterField(
            model_name='macroratio',
            name='fats',
            field=models.FloatField(help_text='Procentaj grăsimi (%)'),
        ),
        migrations.AlterField(
            model_name='macroratio',
            name='fiber_per_day',
            field=models.FloatField(default=30, help_text='Fibre recomandate (g/zi)'),
        ),
        migrations.AlterField(
            model_name='macroratio',
            name='proteins',
            field=models.FloatField(help_text='Procentaj proteine (%)'),
        ),
    ]
