# Generated by Django 5.1.14 on 2025-11-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_macroratio_description_alter_macroratio_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='activity_level',
            field=models.CharField(choices=[('sedentar', 'Sedentar'), ('usor', 'Ușoară'), ('moderata', 'Moderată'), ('intensa', 'Intensă'), ('foarte_intensa', 'Foarte intensă')], max_length=20),
        ),
    ]
