# Generated by Django 5.1.14 on 2025-11-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_mealplan_activity_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='macroratio',
            options={'verbose_name': 'Raport Nutrițional', 'verbose_name_plural': 'Rapoarte Nutriționale'},
        ),
        migrations.AlterModelOptions(
            name='mealplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Plan Alimentar', 'verbose_name_plural': 'Planuri Alimentare'},
        ),
        migrations.AddField(
            model_name='mealplan',
            name='bmi',
            field=models.FloatField(blank=True, help_text='BMI la momentul creării', null=True),
        ),
        migrations.AlterField(
            model_name='macroratio',
            name='description',
            field=models.CharField(blank=True, help_text='Explicație pentru utilizator', max_length=200),
        ),
    ]
