# Generated by Django 5.1.14 on 2025-11-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_macroratio_options_alter_mealplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='target_weight',
            field=models.FloatField(blank=True, help_text='Greutate țintă (kg)', null=True),
        ),
    ]
