# Generated by Django 5.1.14 on 2025-11-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mealplan_target_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
